spring:
                    rabbitmq:
                      host: localhost
                      username: admin
                      password: 123456
                      port: 5672
                      virtual-host: /